CREATE TABLE IF NOT EXISTS Recetas (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMPNIT VARCHAR(50) NOT NULL,
  CODPACIENTE INT NOT NULL,
  FECHA DATE NOT NULL,
  HORA VARCHAR(5) NOT NULL,
  DETALLE JSON NULL,
  INDEX idx_recetas_empnit_fecha (EMPNIT, FECHA),
  INDEX idx_recetas_paciente (EMPNIT, CODPACIENTE)
);
