CREATE TABLE IF NOT EXISTS transacciones (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMPNIT VARCHAR(50) NOT NULL,
  CODPACIENTE INT NOT NULL,
  FECHA DATE NOT NULL,
  TIPO VARCHAR(10) NOT NULL,
  MONTO DECIMAL(12, 2) NOT NULL,
  OBS VARCHAR(500) NULL,
  INDEX idx_transacciones_empnit_fecha (EMPNIT, FECHA),
  INDEX idx_transacciones_paciente (EMPNIT, CODPACIENTE)
);
